FROM openjdk:8-jre-slim
COPY target/videoclubCloudConfigServer-0.0.1-SNAPSHOT.jar /
COPY target/config-Server-videoclub /config-Server-videoclub
EXPOSE 8080
CMD java -jar /videoclubCloudConfigServer-0.0.1-SNAPSHOT.jar